# Generated by Django 2.0.2 on 2018-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recon', '0002_reactionsmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoichiometryMetabolite1',
            fields=[
                ('metabolite', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
